#!/bin/bash

ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.config ~/.config
ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.tmux ~/.tmux
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.oh-my-zsh ~/.oh-my-zsh
ln -s ~/dotfiles/.vim ~/.vim
ln -s ~/dotfiles/.viminfo ~/.viminfo
ln -s ~/dotfiles/.p10k.zsh ~/.p10k.zsh
