#!/bin/bash

ln -s $HOME/dotfiles/.bashrc $HOME/.bashrc
ln -s $HOME/dotfiles/.config $HOME/.config

#tmux
mkdir -p $HOME/.tmux/plugins
git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm # install tpm
ln -s $HOME/dotfiles/.tmux.conf $HOME/.tmux.conf

#vim
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
ln -s $HOME/dotfiles/.vim $HOME/.vim
ln -s $HOME/dotfiles/.viminfo $HOME/.viminfo

#zsh
ln -s $HOME/dotfiles/.zshrc $HOME/.zshrc
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k
ln -s $HOME/dotfiles/.oh-my-zsh $HOME/.oh-my-zsh
ln -s $HOME/dotfiles/.p10k.zsh $HOME/.p10k.zsh
