vim.wo.number = true
vim.wo.relativenumber = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.opt.colorcolumn = { "79", "99", "119" }
vim.g.python3_host_prog = os.getenv("HOME") .. "/.pyenv/bin/python3";
vim.g.python_host_prog = os.getenv("HOME") .. "/.pyenv/bin/python";
